// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ASMEditor': string;
  'ASMEditorPCLine': string;
  'ace_breakpoint': string;
  'ace_gutter-cell': string;
}
declare const cssExports: CssExports;
export = cssExports;
