// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MemoryViewBody': string;
  'StackViewBody': string;
  'Window': string;
  'WindowFooter': string;
  'WindowHeader': string;
  'btn': string;
  'container': string;
}
declare const cssExports: CssExports;
export = cssExports;
